sudo: required
services:
  - docker
script: ./scripts/release-build.sh
after_success:
  - if [ "${TRAVIS_BRANCH}" == "master" ]; then
    docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}";
    docker tag flogo/flogo-contrib:
    docker push pdhar/flogo-contrib;
    fi
